# version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: resource-backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      # dockerfile: ./compose/local/fastapi/Dockerfile
    image: celery_worker
    command: /bin/sh -c "/resource-backend/start-worker.sh"
    volumes:
      - .:/resource-backend
    depends_on:
      - redis
