RESOURCES = {
    "pages": [
        [
            {"id": 1, "title": "title 1"},
            {"id": 2, "title": "title 2"},
            {"id": 3, "title": "title 3"},
            {"id": 4, "title": "title 4"},
            {"id": 5, "title": "title 5"},
            {"id": 6, "title": "title 6"},
            {"id": 7, "title": "title 7"},
            {"id": 8, "title": "title 8"},
            {"id": 9, "title": "title 9"},
            {"id": 10, "title": "title 10"},
            {"id": 11, "title": "title 11"},
            {"id": 12, "title": "title 12"},
            {"id": 13, "title": "title 13"},
            {"id": 14, "title": "title 14"},
            {"id": 15, "title": "title 15"},
            {"id": 16, "title": "title 16"},
            {"id": 17, "title": "title 17"},
            {"id": 18, "title": "title 18"},
            {"id": 19, "title": "title 19"},
            {"id": 20, "title": "title 20"},
        ], 
        [
            {"id": 21, "title": "title 21"},
            {"id": 22, "title": "title 22"},
            {"id": 23, "title": "title 23"},
            {"id": 24, "title": "title 24"},
            {"id": 25, "title": "title 25"},
            {"id": 26, "title": "title 26"},
            {"id": 27, "title": "title 27"},
            {"id": 28, "title": "title 28"},
            {"id": 29, "title": "title 29"},
            {"id": 30, "title": "title 30"},
            {"id": 31, "title": "title 31"},
            {"id": 32, "title": "title 32"},
            {"id": 33, "title": "title 33"},
            {"id": 34, "title": "title 34"},
            {"id": 35, "title": "title 35"},
            {"id": 36, "title": "title 36"},
            {"id": 37, "title": "title 37"},
            {"id": 38, "title": "title 38"},
            {"id": 39, "title": "title 39"},
            {"id": 40, "title": "title 40"},
        ],
        [
            {"id": 41, "title": "title 41"},
            {"id": 42, "title": "title 42"},
            {"id": 43, "title": "title 43"},
            {"id": 44, "title": "title 44"},
            {"id": 45, "title": "title 45"},
            {"id": 46, "title": "title 46"},
            {"id": 47, "title": "title 47"},
            {"id": 48, "title": "title 48"},
            {"id": 49, "title": "title 49"},
            {"id": 50, "title": "title 50"},
            {"id": 51, "title": "title 51"},
            {"id": 52, "title": "title 52"},
            {"id": 53, "title": "title 53"},
            {"id": 54, "title": "title 54"},
            {"id": 55, "title": "title 55"},
            {"id": 56, "title": "title 56"},
            {"id": 57, "title": "title 57"},
            {"id": 58, "title": "title 58"},
            {"id": 59, "title": "title 59"},
            {"id": 60, "title": "title 60"},
        ],
        [
            {"id": 61, "title": "title 61"},
            {"id": 62, "title": "title 62"},
            {"id": 63, "title": "title 63"},
            {"id": 64, "title": "title 64"},
            {"id": 65, "title": "title 65"},
            {"id": 66, "title": "title 66"},
            {"id": 67, "title": "title 67"},
            {"id": 68, "title": "title 68"},
            {"id": 69, "title": "title 69"},
            {"id": 70, "title": "title 70"},
            {"id": 71, "title": "title 71"},
            {"id": 72, "title": "title 72"},
            {"id": 73, "title": "title 73"},
            {"id": 74, "title": "title 74"},
            {"id": 75, "title": "title 75"},
            {"id": 76, "title": "title 76"},
            {"id": 77, "title": "title 77"},
            {"id": 78, "title": "title 78"},
            {"id": 79, "title": "title 79"},
            {"id": 80, "title": "title 80"},
        ]
    ]
}
