name: Linting workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check format with Black
        run: |
          pip install black
          black app/
        continue-on-error: true

      - name: Lint with Pylint
        run: |
          pip install pylint
          pylint app/
        continue-on-error: true

      - name: Type checking with mypy
        run: |
          pip install mypy
          mypy app/
        continue-on-error: true
